@startuml
autonumber
actor 上位机

上位机 -> 蓝牙集中器 : 485发送iot 类型【电信、移动】
蓝牙集中器 --> 上位机: 确认配置信息
上位机 -> 蓝牙集中器 : 485设置逻辑地址（12位）
蓝牙集中器 --> 上位机: 确认配置信
上位机 -> bbiiot : 推送集中器号，iot 类型，imei
bbiiot -> 运营商iot : 注册 imei
bbiiot <-- 运营商iot : 确认 imei
bbiiot-->上位机:确认报文

上位机 -> 蓝牙集中器 : 设置集中器时钟
蓝牙集中器 --> 上位机: 确认配置信息
蓝牙集中器 -> 蓝牙集中器 : NB上线
手机->蓝牙集中器:蓝牙连接
上位机 -> 蓝牙集中器 : 除通讯参数外的数据复位
蓝牙集中器 --> 上位机: 确认配置信息


上位机 -> 蓝牙集中器 : 读取集中器版本
蓝牙集中器 --> 上位机: 确认配置信息

  

@enduml